from tkinter import *
top =  Tk()
top.title("demo")
top.geometry("500x300")
name=Label(top,text="username")
e1=Entry(top)
name.grid(row=0,column=0,padx=0,pady=0)
e1.grid(row=0,column=1,padx=10,pady=5)
bro=Label(top,text="password")
bro.grid(row=1,column=0,padx=0,pady=0)
e2=Entry(top)
e2.grid(row=1,column=1,padx=10,pady=5)
btn=Button(text="Login")
btn.grid(row=2,column=0)
top.mainloop()
